### ISSUE TITLE
Pick 12 Ingredients

### ISSUE THREAD

**Issue by StachuDotNet** [kunjee17/ask-me-anything#1]
If you had to pick 12 ingredients to eat and create food from for the rest of your life, what are the 12?

Spices don't count - assume you have a reasonable supply of spices.
Naturally, water is a freebie as well.

**Comment by kunjee17** [comment]
Thanks @kunjee17 for asking. But I guess 12 is too less even for simple dish. But still let me try to answer this with my favorite recipe `Undhiyu` . 

1.  Chopped fenugreek 
2. whole wheat floor
3. besan
4. baby potatoes
5. banana
6. brinjal / eggplant
7. surti papdi
8. purple yum
9. toovar
10. carom seeds
11. coconut
12. Green chilies

I did have skipped spices, water and oil. 

Still curious have a look at [recipe](https://www.tarladalal.com/Oondhiya-Undhiyu-Gujarati-Undhiyu-Recipe-602r) and give it try at home. You might like it.
